name: timezone
version: 0.9.2
description: Time zone database and time zone aware DateTime.
repository: https://github.com/srawlins/timezone
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  path: ^1.8.0
dev_dependencies:
  args: any
  file: ^6.0.0
  glob: ^2.0.0
  lints: ^2.0.0
  logging: any
  test: ^1.16.0
